
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author trananh bacninh
 */
public class FormNhapDiem extends javax.swing.JDialog {
    private String khoiThi;
    private NhapDiem nhapDiem;
    private ArrayList<Double>listDiem=new ArrayList();
    private String loaiNhap;
    /**
     * Creates new form FormNhapDiem
     */
    public FormNhapDiem(String khoiThi,NhapDiem nhapDiem,String loaiNhap) {
        this.khoiThi=khoiThi;
        this.setTitle("Nhập điểm");
        this.nhapDiem=nhapDiem;
        this.loaiNhap=loaiNhap;
        initComponents();
        switch(this.khoiThi){
            case "A":
                System.out.println("A");
                this.jL_Mon1.setText("Toán");
                this.jL_Mon2.setText("Vật lý");
                this.jL_Mon3.setText("Hóa học");
                break;
            case "B":
                this.jL_Mon1.setText("Toán");
                this.jL_Mon2.setText("Hóa học");
                this.jL_Mon3.setText("Sinh học");
                break;
            case "C":
                this.jL_Mon1.setText("Ngữ văn");
                this.jL_Mon2.setText("Lịch sử");
                this.jL_Mon3.setText("Địa lý");
                break;
            case "D":
                
                this.jL_Mon1.setText("Ngữ văn");
                this.jL_Mon2.setText("Toán");
                this.jL_Mon3.setText("Tiếng anh");
                break;
            case "A1":
                System.out.println("A1");
                System.out.println("A1");
                this.jL_Mon1.setText("Toán");
                this.jL_Mon2.setText("Vật lý");
                this.jL_Mon3.setText("Tiếng anh");
                break;
                
        }
        if(loaiNhap.equals("Lớp 12")){
            this.jL_Title.setText("Nhập điểm lớp 12");
        }else{
            this.jL_Title.setText("Nhập điểm thi thử");
        }
        
        this.setVisible(true);
    }
    private void getListDiem(){
        try{
       int dem=0;
       Double diem1=new Double(this.jT_Mon1.getText());
       if((diem1.doubleValue())>10||(diem1.doubleValue()<0)){
           JOptionPane.showMessageDialog(this,"Điểm môn thứ nhất không hợp lệ");
           diem1=new Double("0");
           dem++;
       }
       Double diem2=new Double(this.jT_Mon2.getText());
       if((diem2.doubleValue())>10||(diem2.doubleValue()<0)){
           JOptionPane.showMessageDialog(this,"Điểm môn thứ 2 không hợp lệ");
           diem2=new Double("0");
           dem++;
       }
       Double diem3=new Double(this.jT_Mon3.getText());
      if((diem3.doubleValue())>10||(diem3.doubleValue()<0)){
           JOptionPane.showMessageDialog(this,"Điểm môn thứ 3 không hợp lệ");
           diem3=new Double("0");
           dem++;
       }
      this.listDiem.add(diem1);
      this.listDiem.add(diem2);
      this.listDiem.add(diem3);
      if(dem==0){
          this.setVisible(false);
      }
       }catch(Exception e){
           JOptionPane.showMessageDialog(this,"Dữ liệu không hợp lệ");
           this.listDiem=new ArrayList();
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_Mon1 = new javax.swing.JLabel();
        jL_Mon2 = new javax.swing.JLabel();
        jL_Mon3 = new javax.swing.JLabel();
        jL_Title = new javax.swing.JLabel();
        jB_OK = new javax.swing.JButton();
        jT_Mon1 = new javax.swing.JTextField();
        jT_Mon2 = new javax.swing.JTextField();
        jT_Mon3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jL_Mon1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jL_Mon1.setForeground(new java.awt.Color(153, 0, 153));
        jL_Mon1.setText("<html><u>Toán</u></html>");
        jL_Mon1.setToolTipText("");

        jL_Mon2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jL_Mon2.setForeground(new java.awt.Color(204, 0, 204));
        jL_Mon2.setText("<html><u>Lý</u></html>");

        jL_Mon3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jL_Mon3.setForeground(new java.awt.Color(204, 0, 204));
        jL_Mon3.setText("<html><u>Hóa</u></html>");

        jL_Title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jL_Title.setForeground(new java.awt.Color(51, 0, 255));
        jL_Title.setText("Nhập điểm");

        jB_OK.setText("OK");
        jB_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_OKActionPerformed(evt);
            }
        });

        jT_Mon1.setToolTipText("");
        jT_Mon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_Mon1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_Title)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jL_Mon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jL_Mon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jL_Mon3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jT_Mon1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jT_Mon2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jT_Mon3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB_OK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_Mon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jT_Mon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_Mon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jT_Mon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_Mon3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jT_Mon3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jB_OK)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_OKActionPerformed
        // TODO add your handling code here:
        this.listDiem=new ArrayList();
        this.getListDiem();
        if(this.loaiNhap.equals("Lớp 12")){
          this.nhapDiem.setListDiem12(this.listDiem, khoiThi);  
        }else{
            this.nhapDiem.setListDiemThiThu(this.listDiem);
        }
        
        
     
        
       
       
        
    }//GEN-LAST:event_jB_OKActionPerformed

    private void jT_Mon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_Mon1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_Mon1ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_OK;
    private javax.swing.JLabel jL_Mon1;
    private javax.swing.JLabel jL_Mon2;
    private javax.swing.JLabel jL_Mon3;
    private javax.swing.JLabel jL_Title;
    private javax.swing.JTextField jT_Mon1;
    private javax.swing.JTextField jT_Mon2;
    private javax.swing.JTextField jT_Mon3;
    // End of variables declaration//GEN-END:variables
}

