
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author trananh bacninh
 */
public class GiaoDien1 extends javax.swing.JFrame implements NhapDiem {
    private  HocSinh hocSinh=new HocSinh();
    private Database database=new Database();
    /**
     * Creates new form GiaoDien1
     */
    public GiaoDien1() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setTitle("Tư vấn trường đại học");
        //Set giá trị cho mục sở thích
        this.setListSoThich();
        this.setListAddress();
        
    }
    //Hàm set giá trị cho mục sở thích
    public  void setListSoThich(){
        ArrayList<String> dsSoThich=database.layDanhSachSoThich();
        String[] list=new String[dsSoThich.size()];
        for(int i=0;i<dsSoThich.size();i++){
            list[i]=dsSoThich.get(i);
        }
        
        DefaultComboBoxModel model=new DefaultComboBoxModel(list);
        this.jCBSoThich.setModel(model);
    }
    //Hàm set giá trị cho mục địa chỉ
    public void setListAddress(){
        DefaultComboBoxModel model=new DefaultComboBoxModel(database.getListNameCity());
        this.jCB_DiaDiem.setModel(model);
    }
    //Hàm để lấy toàn bộ thông tin của học sinh
    private void setThongTinHocSinh(){
        this.hocSinh.setSoThich(this.jCBSoThich.getSelectedItem().toString());
        if(this.jRadioButton_Nam.isSelected()){
            this.hocSinh.setGioiTinh("Nam");
        }else{
            this.hocSinh.setGioiTinh("Nu");
        }
        this.hocSinh.setKhaNangTaiChinh(this.jCB_KhaNangTaiChinh.getSelectedItem().toString());
        this.hocSinh.setKhuVucUuTien(this.jCB_KhuVucUuTien.getSelectedItem().toString());
        this.hocSinh.setUuTienDacBiet(this.jCB_KhuVucDacBiet.getSelectedItem().toString());
        this.hocSinh.setDiaDiem(this.jCB_DiaDiem.getSelectedItem().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupGioitinh = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCBSoThich = new javax.swing.JComboBox<>();
        jRadioButton_Nam = new javax.swing.JRadioButton();
        jRadioButton_Nu = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jCB_KhoiThi = new javax.swing.JComboBox<>();
        jB_TuVan = new javax.swing.JButton();
        jB_Thoat = new javax.swing.JButton();
        jL_DanhSachTruong = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jBtnNhapDiemThiThu = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jCB_KhaNangTaiChinh = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jCB_KhuVucUuTien = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jCB_KhuVucDacBiet = new javax.swing.JComboBox<>();
        jBtnNhapDiemTongKet = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jCB_DiaDiem = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Tư vấn chọn trường đại học");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setText("<html><u>Sở thích</u></html>");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 255));
        jLabel3.setText("<html><u>Giới tính</u></html>");

        jCBSoThich.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCBSoThich.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Khoa Hoc Cong Nghe", "Am Thuc", "Ky Su Xay Dung", "Bac Sy", "Luat Su", "Nha Bao", "Phong Vien", "Van Hoc", "Ngoai Ngu", "San Khau Dien Anh" }));
        jCBSoThich.setToolTipText("");

        buttonGroupGioitinh.add(jRadioButton_Nam);
        jRadioButton_Nam.setSelected(true);
        jRadioButton_Nam.setText("Nam");
        jRadioButton_Nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_NamActionPerformed(evt);
            }
        });

        buttonGroupGioitinh.add(jRadioButton_Nu);
        jRadioButton_Nu.setText("Nữ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 204));
        jLabel4.setText("<html><u>Khối thi</u></html>");

        jCB_KhoiThi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCB_KhoiThi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "A1", "B", "C", "D" }));
        jCB_KhoiThi.setToolTipText("");

        jB_TuVan.setBackground(new java.awt.Color(255, 255, 255));
        jB_TuVan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jB_TuVan.setForeground(new java.awt.Color(255, 0, 51));
        jB_TuVan.setText("Tư vấn");
        jB_TuVan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_TuVanActionPerformed(evt);
            }
        });

        jB_Thoat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jB_Thoat.setForeground(new java.awt.Color(204, 0, 51));
        jB_Thoat.setText("Thoát");
        jB_Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_ThoatActionPerformed(evt);
            }
        });

        jL_DanhSachTruong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jL_DanhSachTruong.setForeground(new java.awt.Color(51, 153, 255));
        jL_DanhSachTruong.setText("<html><u>Danh sách các trường</u><html>");
        jL_DanhSachTruong.setToolTipText("");
        jL_DanhSachTruong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_DanhSachTruongMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("<html><u>Điểm tổng kết lớp 12</u></html>");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("<html><u>Điểm thi thử các môn gần nhất</u></html>");

        jBtnNhapDiemThiThu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBtnNhapDiemThiThu.setForeground(new java.awt.Color(255, 0, 51));
        jBtnNhapDiemThiThu.setText("Nhập điểm");
        jBtnNhapDiemThiThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNhapDiemThiThuActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 255));
        jLabel8.setText("<html><u>Khả năng tài chính</u></html>");

        jCB_KhaNangTaiChinh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCB_KhaNangTaiChinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thấp", "Trung Bình", "Cao" }));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 255));
        jLabel9.setText("<html><u>Khu vực ưu tiên</u></html>");

        jCB_KhuVucUuTien.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCB_KhuVucUuTien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KV1", "KV2", "KV2 NT", "KV3" }));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 255));
        jLabel10.setText("<html><u>Ưu tiên đặc biệt</u></html>");

        jCB_KhuVucDacBiet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Không", "Gia đình quân đội", "Gia đình thương binh liệt sĩ", "Cả hai" }));
        jCB_KhuVucDacBiet.setToolTipText("");

        jBtnNhapDiemTongKet.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBtnNhapDiemTongKet.setForeground(new java.awt.Color(255, 0, 0));
        jBtnNhapDiemTongKet.setText("Nhập điểm");
        jBtnNhapDiemTongKet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNhapDiemTongKetActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 153));
        jLabel5.setText("<html><u>Địa chỉ</u></html>");
        jLabel5.setToolTipText("");

        jCB_DiaDiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hà Nội", "Hải Phòng", "Hải Dương", "Hà Nam", "Bắc Ninh", "Hưng Yên", "Nam Định", "Ninh Bình", "Thái Bình", "Vĩnh Phúc", "Bắc Giang" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jL_DanhSachTruong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jB_TuVan)
                        .addGap(18, 18, 18)
                        .addComponent(jB_Thoat)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCB_KhoiThi, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jRadioButton_Nam)
                                                .addGap(27, 27, 27)
                                                .addComponent(jRadioButton_Nu)))
                                        .addGap(275, 275, 275))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCBSoThich, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(195, 195, 195))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnNhapDiemTongKet)
                                .addGap(235, 235, 235)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCB_KhaNangTaiChinh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCB_KhuVucUuTien, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnNhapDiemThiThu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jCB_KhuVucDacBiet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jCB_DiaDiem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCBSoThich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnNhapDiemThiThu)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton_Nam)
                    .addComponent(jRadioButton_Nu)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCB_KhaNangTaiChinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCB_KhoiThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCB_KhuVucUuTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCB_KhuVucDacBiet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnNhapDiemTongKet))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCB_DiaDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_TuVan)
                    .addComponent(jB_Thoat)
                    .addComponent(jL_DanhSachTruong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnNhapDiemThiThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNhapDiemThiThuActionPerformed
        // TODO add your handling code here:
       
       
        
        FormNhapDiem form=new FormNhapDiem(this.hocSinh.getKhoiThi(),(NhapDiem)this,"Thi thử");
        form.setLocationRelativeTo(this);
        
    }//GEN-LAST:event_jBtnNhapDiemThiThuActionPerformed

    private void jB_TuVanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_TuVanActionPerformed
        // TODO add your handling code here:
        
       
        
        this.setThongTinHocSinh();
        System.out.println(hocSinh.hienThiThongTin());
        if(this.hocSinh.getListDiemThiThu().size()!=3 || this.hocSinh.getListDiemTongKet12().size()!=3){
            JOptionPane.showMessageDialog(null,"Chưa nhập điểm");
        }else{
        ArrayList<School> schools=(new Core(this.hocSinh)).start();
        
        new FormKetQuaTuVan(schools);
        System.out.println(this.hocSinh.hienThiThongTin());
        }
    }//GEN-LAST:event_jB_TuVanActionPerformed

    private void jB_ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_ThoatActionPerformed
            // TODO add your handling code here:
            System.exit(0);
    }//GEN-LAST:event_jB_ThoatActionPerformed

    private void jBtnNhapDiemTongKetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNhapDiemTongKetActionPerformed
        // TODO add your handling code here:
        String khoiThi=this.jCB_KhoiThi.getSelectedItem().toString();
        this.hocSinh.setKhoiThi(khoiThi);
        
        FormNhapDiem form=new FormNhapDiem(khoiThi,(NhapDiem)this,"Lớp 12");
        form.setLocationRelativeTo(this);
    }//GEN-LAST:event_jBtnNhapDiemTongKetActionPerformed

    private void jL_DanhSachTruongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_DanhSachTruongMouseClicked
        // TODO add your handling code here:
        new FormDanhSachTruong();
    }//GEN-LAST:event_jL_DanhSachTruongMouseClicked

    private void jRadioButton_NamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_NamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_NamActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupGioitinh;
    private javax.swing.JButton jB_Thoat;
    private javax.swing.JButton jB_TuVan;
    private javax.swing.JButton jBtnNhapDiemThiThu;
    private javax.swing.JButton jBtnNhapDiemTongKet;
    private javax.swing.JComboBox<String> jCBSoThich;
    private javax.swing.JComboBox<String> jCB_DiaDiem;
    private javax.swing.JComboBox<String> jCB_KhaNangTaiChinh;
    private javax.swing.JComboBox<String> jCB_KhoiThi;
    private javax.swing.JComboBox<String> jCB_KhuVucDacBiet;
    private javax.swing.JComboBox<String> jCB_KhuVucUuTien;
    private javax.swing.JLabel jL_DanhSachTruong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton_Nam;
    private javax.swing.JRadioButton jRadioButton_Nu;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setListDiem12(ArrayList<Double>listDiem,String khoiThi) {
        this.hocSinh.setListDiemTongKet12(listDiem);
        this.hocSinh.setKhoiThi(khoiThi);
    }

    @Override
    public void setListDiemThiThu(ArrayList<Double>listDiem) {
        this.hocSinh.setListDiemThiThu(listDiem);
        
    }
}
     interface NhapDiem{
    public void setListDiem12(ArrayList<Double> listDiem,String khoiThi);
    public void setListDiemThiThu(ArrayList<Double>listDiem);
}
